name: Generate Profile Stats Cards
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: 'username=julianabanana&show_icons=true&theme=sakura'
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: 'username=julianabanana&layout=compact&langs_count=8&theme=sakura'
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update GitHub stats SVGs"
